name: Run R Script

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 15:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_TOKEN }}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("dplyr", "purrr", "stringr", "janitor", "readxl", "ggplot2", "showtext", "lubridate"), repos = "https://cloud.r-project.org")'

    - name: Run the main script
      run: |
        Rscript data_analysis.R

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "actions@users.noreply.github.com"
        git diff --exit-code || echo "Changes detected"
        git add -A
        git commit -m "Auto-commit from GitHub Actions at $(date -u)" || echo "No changes to commit"
        git pull --rebase || echo "Nothing to rebase"
        git push || echo "Nothing to push"
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
