name: Run Script

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -r .github/workflows/requirements.txt

    - name: Run the script
      run: |
        python script.py

    - name: Run the script
      run: |
        python deduplicate.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "actions@users.noreply.github.com"
        git diff --exit-code || echo "Changes detected"
        git add -A
        git commit -m "Auto-commit from GitHub Actions at $(date -u)" || echo "No changes to commit"
        git pull --rebase || echo "Nothing to rebase"
        git push || echo "Nothing to push"
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
